We can make use of the dot() for multiplying matrices represented as NumPy arrays.

In [1]:
import numpy as np

# NumPy matrices
A = np.arange(15,24).reshape(3,3)
B = np.arange(20,29).reshape(3,3)
print("A: ",A)
print("B: ",B)

# Multiply A and B
result = A.dot(B)
print("Result: ", result)

A:  [[15 16 17]
 [18 19 20]
 [21 22 23]]
B:  [[20 21 22]
 [23 24 25]
 [26 27 28]]
Result:  [[1110 1158 1206]
 [1317 1374 1431]
 [1524 1590 1656]]


Another Example

In [3]:
import numpy as np

# NumPy matrices
A = np.arange(1,5).reshape(2,2)
B = np.arange(1,5).reshape(2,2)
print("A: ",A)
print("B: ",B)

# Multiply A and B
result = A.dot(B)
print("Result: ", result)

A:  [[1 2]
 [3 4]]
B:  [[1 2]
 [3 4]]
Result:  [[ 7 10]
 [15 22]]
